version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: school_notifier_app
    ports:
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge


